#!/bin/bash

# Load resources

xrdb -merge .Xresources

export GTK_OVERLAY_SCROLLING=0
# Fire up apps
xloadimage -onroot -quiet /home/mindaugas/Pictures/blur.jpeg &
xsetroot -cursor_name left_ptr &
xautolock -time 10 -locker 'xtrlock' &
setxkbmap -layout "us,lt,ru" -option "grp:alt_shift_toggle" &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

exec ratpoison
