#!/bin/bash

# Load resources

xrdb -merge .Xresources

export GTK_OVERLAY_SCROLLING=0
# Fire up apps
xsetroot -cursor_name left_ptr &
/home/mindaugas/.fehbg &
urxvtd -q -f -o &
xautolock -time 10 -locker 'slock' &
setxkbmap -layout "us,lt,ru" -option "grp:ctrl_shift_toggle" &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

exec  xmonad
